<?php

const CARDIOMET_PREMISSION_PRINT_LABELS = 'CARDIOMET print labels';

function cardiomet_permission() {
  return array(
    CARDIOMET_PREMISSION_PRINT_LABELS => array (
      'title' => t(CARDIOMET_PREMISSION_PRINT_LABELS), 
      'description' => t(CARDIOMET_PREMISSION_PRINT_LABELS),
    ),
  );
}

function cardiomet_label_printer_populateDefinitions(array &$definitions) {
  $definitions['CARDIOMET Pack'] = array(
      'name' => 'CARDIOMET Pack',
      'permission' => CARDIOMET_PREMISSION_PRINT_LABELS,
      'participant_id_generators' => array(
        'study_id' => new IdGenerator('CarPt'),
        ),
      'labels' => array(
        'Brown Aortic Rest' => array(
          'id_generator' => new IdGenerator('CarSa'),
          'printer' => LabelPrinter::PRINTER_CVRC_LAB_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 1,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => 'Aortic Rest 9.8ml (Serum - BROWN)'
            )
          ),
        'Orange Aortic Rest' => array(
          'id_generator' => new IdGenerator('CarSa'),
          'printer' => LabelPrinter::PRINTER_CVRC_LAB_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 1,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => 'Aortic Rest 9.8ml (Heparin - ORANGE)'
            )
          ),
        'Brown CS Rest' => array(
          'id_generator' => new IdGenerator('CarSa'),
          'printer' => LabelPrinter::PRINTER_CVRC_LAB_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 1,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => 'CS Rest 9.8ml (Serum - BROWN)'
            )
          ),
        'Orange CS Rest' => array(
          'id_generator' => new IdGenerator('CarSa'),
          'printer' => LabelPrinter::PRINTER_CVRC_LAB_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 1,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => 'CS Rest 9.8ml (Heparin - ORANGE)'
            )
          ),
        'Brown Aortic Stress' => array(
          'id_generator' => new IdGenerator('CarSa'),
          'printer' => LabelPrinter::PRINTER_CVRC_LAB_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 1,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => 'Aortic Stress 9.8ml (Serum - BROWN)'
            )
          ),
        'Orange Aortic Stress' => array(
          'id_generator' => new IdGenerator('CarSa'),
          'printer' => LabelPrinter::PRINTER_CVRC_LAB_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 1,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => 'Aortic Stress 9.8ml (Heparin - ORANGE)'
            )
          ),
        'Brown CS Stress' => array(
          'id_generator' => new IdGenerator('CarSa'),
          'printer' => LabelPrinter::PRINTER_CVRC_LAB_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 1,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => 'CS Stress 9.8ml (Serum - BROWN)'
            )
          ),
        'Orange CS Stress' => array(
          'id_generator' => new IdGenerator('CarSa'),
          'printer' => LabelPrinter::PRINTER_CVRC_LAB_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 1,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => 'CS Stress 9.8ml (Heparin - ORANGE)'
            )
          ),
        'Brown Visit 2' => array(
          'id_generator' => new IdGenerator('CarSa'),
          'printer' => LabelPrinter::PRINTER_CVRC_LAB_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 1,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => '2nd Visit 9.8ml (Serum - BROWN)'
            )
          ),
        'Orange Visit 2' => array(
          'id_generator' => new IdGenerator('CarSa'),
          'printer' => LabelPrinter::PRINTER_CVRC_LAB_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 1,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => '2nd Visit 9.8ml (Heparin - ORANGE)'
            )
          ),
        'Participant Label' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE,
          'id_count' => 1,
          'labels_per_id' => 3
          ),
        'Visit 1 Aortic Rest Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_BAG_CARDIOMET_VISIT,
          'study_name' => 'CARDIOMET V1 Aortic Rest',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        'Visit 1 CS Rest Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_BAG_CARDIOMET_VISIT,
          'study_name' => 'CARDIOMET V1 CS Rest',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        'Visit 1 Aortic Stress Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_BAG_CARDIOMET_VISIT,
          'study_name' => 'CARDIOMET V1 Aortic Stress',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        'Visit 1 CS Stress Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_BAG_CARDIOMET_VISIT,
          'study_name' => 'CARDIOMET V1 CS Stress',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        'Visit 2 Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_BAG_CARDIOMET_VISIT,
          'study_name' => 'CARDIOMET V2',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        ),
    );
}
