<?php

const CARDIOMET_PREMISSION_PRINT_LABELS = 'CARDIOMET print labels';

function cardiomet_permission() {
  return array(
    CARDIOMET_PREMISSION_PRINT_LABELS => array (
      'title' => t(CARDIOMET_PREMISSION_PRINT_LABELS), 
      'description' => t(CARDIOMET_PREMISSION_PRINT_LABELS),
    ),
  );
}

function cardiomet_label_printer_populateDefinitions(array &$definitions) {
  $definitions['CARDIOMET Pack'] = array(
      'name' => 'CARDIOMET Pack',
      'permission' => CARDIOMET_PREMISSION_PRINT_LABELS,
      'participant_id_generators' => array(
        'study_id' => new IdGenerator('CarPt'),
        ),
      'labels' => array(
        'Serun Samples' => array(
          'id_generator' => new IdGenerator('CarSa'),
          'printer' => LabelPrinter::PRINTER_BRU_CRF_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 4,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => '4.9ml Serum'
            )
          ),
        'Participant Label' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE,
          'id_count' => 1,
          'labels_per_id' => 3
          ),
        'Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_BAG_CARDIOMET,
          'study_name' => 'CARDIOMET',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        ),
    );
}
