<?php


const INDAPAMIDE_PREMISSION_PRINT_LABELS = 'Indapamide print labels';


function indapamide_permission() {
  return array(
    INDAPAMIDE_PREMISSION_PRINT_LABELS => array (
      'title' => t(INDAPAMIDE_PREMISSION_PRINT_LABELS), 
      'description' => t(INDAPAMIDE_PREMISSION_PRINT_LABELS),
    ),
  );
}


function indapamide_civicrm_validateForm( $formName, &$fields, &$files, &$form, &$errors ) {

    $contactFormBeginning = 'CRM_Case_Form_';

    if (lcbru_string_starts_with($formName, $contactFormBeginning)) {
        foreach ($fields as $key => $field) {
            if (lcbru_string_starts_with($key, lcbru_get_custom_field_id_name(CIVI_FIELD_INDAPAMIDE_ID) . '_')) {
                if (_interval_isInvalidIntervalId($field)) {
                    $errors[$key] = ts(CIVI_FIELD_INDAPAMIDE_ID . " is not valid.  Should be a 8 digit number");
                }
            }
        }
    }
    return;
}


function _indapamide_isInvalidIntervalId($value) {
  $idGenerator = new IdGenerator('IndPt');

  return !$idGenerator->validate($value);
}


function indapamide_lcbru_populateStudyIds(array &$studyIds) {
    $studyIds[] = 'CIVI_FIELD_INDAPAMIDE_ID';
}


function indapamide_lcbru_getStudyIdFieldName($studyId) {
    if (!_indapamide_isInvalidIntervalId($studyId)) {
        return 'CIVI_FIELD_INDAPAMIDE_ID';   
    }
}


function indapamide_lcbru_getAutoCustomFieldValue($fieldName) {
    Guard::AssertString_NotEmpty('$fieldName', $fieldName);

    switch ($fieldName) {
        case 'CIVI_FIELD_INDAPAMIDE_ID':
            $studyIdGenerator = new IdGenerator('IndPt');
            return $studyIdGenerator->next();
            break;
    }
}


function indapamide_label_printer_populateDefinitions(array &$definitions) {
  $definitions['Indapamide Pack'] = array(
      'name' => 'Indapamide Pack',
      'permission' => INDAPAMIDE_PREMISSION_PRINT_LABELS,
      'participant_id_generators' => array(
        'study_id' => new IdGenerator('IndPt'),
        ),
      'labels' => array(
        'EDTA Samples' => array(
          'id_generator' => new IdGenerator('IndSa'),
          'printer' => LabelPrinter::PRINTER_BRU_CRF_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 8,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => 'EDTA 7.5ml On ice'
            )
          ),
        'SERUM samples' => array(
          'id_generator' => new IdGenerator('IndSa'),
          'printer' => LabelPrinter::PRINTER_BRU_CRF_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 4,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => 'SERUM 4.9ml Room temp'
            )
          ),
        'URINE samples' => array(
          'id_generator' => new IdGenerator('IndSa'),
          'printer' => LabelPrinter::PRINTER_BRU_CRF_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE_AND_MESSAGE,
          'id_count' => 4,
          'labels_per_id' => 1,
          'fields' => array(
            '{MESSAGE_PLACEHOLDER}' => 'URINE 50ml On ice'
            )
          ),

        'Participant Label' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_SAMPLE,
          'template' => LabelPrinter::LABEL_SAMPLE,
          'id_count' => 1,
          'labels_per_id' => 4
          ),

        'Visit 1 Serum Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_INDAPAMIDE_SERUM_BAG,
          'study_name' => 'Ind Baseline',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        'Visit 1 EDTA Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_INDAPAMIDE_EDTA_BAG,
          'study_name' => 'Ind Baseline',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        'Visit 1 URINE Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_INDAPAMIDE_URINE_BAG,
          'study_name' => 'Ind Baseline',
          'id_count' => 1,
          'labels_per_id' => 1
          ),

        'Visit 2 Serum Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_INDAPAMIDE_SERUM_BAG,
          'study_name' => 'Ind 2 Weeks',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        'Visit 2 EDTA Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_INDAPAMIDE_EDTA_BAG,
          'study_name' => 'Ind 2 Weeks',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        'Visit 2 URINE Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_INDAPAMIDE_URINE_BAG,
          'study_name' => 'Ind 2 Weeks',
          'id_count' => 1,
          'labels_per_id' => 1
          ),

        'Visit 3 Serum Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_INDAPAMIDE_SERUM_BAG,
          'study_name' => 'Ind 6 Weeks',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        'Visit 3 EDTA Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_INDAPAMIDE_EDTA_BAG,
          'study_name' => 'Ind 6 Weeks',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        'Visit 3 URINE Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_INDAPAMIDE_URINE_BAG,
          'study_name' => 'Ind 6 Weeks',
          'id_count' => 1,
          'labels_per_id' => 1
          ),

        'Visit 4 Serum Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_INDAPAMIDE_SERUM_BAG,
          'study_name' => 'Ind 10 Weeks',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        'Visit 4 EDTA Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_INDAPAMIDE_EDTA_BAG,
          'study_name' => 'Ind 10 Weeks',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        'Visit 4 URINE Bag' => array(
          'participant_id' => 'study_id',
          'printer' => LabelPrinter::PRINTER_BRU_CRF_BAG,
          'template' => LabelPrinter::LABEL_INDAPAMIDE_URINE_BAG,
          'study_name' => 'Ind 10 Weeks',
          'id_count' => 1,
          'labels_per_id' => 1
          ),
        ),
    );
}


function indapamide_participant_importer_populateDefinitions() {
    return array(
        'Indapamide REDCap' => array(
            'query' => "
                SELECT *
                FROM (
                    SELECT
                        MAX(COALESCE(es.ts, 0)) AS last_update,
                        s.record CIVI_FIELD_INDAPAMIDE_ID,
                        s.record,
                        s.project_id,
                        s.start_date,
                        CASE s.gender
                                WHEN 0 THEN 'Female'
                                WHEN 1 THEN 'male'
                             END AS gender,
                        s.birth_date,
                        s.UHL_S_number,
                     CASE
                         WHEN COALESCE(study_status, '1') = '1' THEN 'recruited'
                         WHEN non_complete_rsn = '5' THEN 'withdrawn'
                         ELSE 'excluded'
                     END AS case_status

                     FROM (
                        SELECT
                            rd.record,
                            rd.project_id,
                            GROUP_CONCAT(CASE WHEN field_name = 'study_status' THEN VALUE ELSE NULL END) AS study_status,
                            GROUP_CONCAT(CASE WHEN field_name = 'non_complete_rsn' THEN VALUE ELSE NULL END) AS non_complete_rsn,
                            GROUP_CONCAT(CASE WHEN field_name = 's_number' THEN VALUE ELSE NULL END) AS uhl_s_number,
                            GROUP_CONCAT(CASE WHEN field_name = 'screening_date' THEN VALUE ELSE NULL END) AS start_date,
                            GROUP_CONCAT(CASE WHEN field_name = 'gender' THEN VALUE ELSE NULL END) AS gender,
                            GROUP_CONCAT(CASE WHEN field_name = 'dob' THEN VALUE ELSE NULL END) AS birth_date
                        FROM    redcap_data rd
                        WHERE rd.project_id = 50
                        GROUP BY rd.record, rd.project_id
                    ) s
                    LEFT JOIN redcap_log_event es
                        ON es.project_id = s.project_id
                        AND es.pk = s.record
                        AND es.`event` NOT IN ('DATA_EXPORT', 'DELETE')
                        # Ignore events caused by the data import from
                        # the mobile app
                        AND es.page NOT IN ('DataImportController:index')
                    GROUP BY s.record
                ) x
                WHERE LENGTH(TRIM(COALESCE(CIVI_FIELD_INDAPAMIDE_ID, ''))) > 0
                ",
             'case_type_name' => CIVI_CASE_TYPE_INDAPAMIDE,
             'add_pmi' => 1
        )
    );
}
