CREATE TABLE ice_messaging (
ORDER_ID INT NOT NULL,
ORDER_GROUP_ID INT NOT NULL,
SYSTEM_NUMBER VARCHAR(16) NOT NULL,
NHS_NUMBER VARCHAR(16) NOT NULL,
SURNAME VARCHAR(32) NOT NULL,
FORENAMES VARCHAR(32) NOT NULL,
TITLE VARCHAR(16) NOT NULL,
DATE_OF_BIRTH DATE,
ETHNIC_GROUP VARCHAR(32) NOT NULL,
REFERRAL_SOURCE VARCHAR(16) NOT NULL,
REFERRER VARCHAR(16) NOT NULL,
ORDER_STATUS VARCHAR(16) NOT NULL,
GENDER VARCHAR(32) NOT NULL,
TRANSACTION_DATE_TIME DATETIME NOT NULL,
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PROCESSED CHAR(1) NOT NULL
);


